export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST'
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS'
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL'

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST'
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS'
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL'
